fos_rest:
  format_listener:
    rules:
      - { path: ^/v1, prefer_extension: true, fallback_format: json, priorities: [ json, html ] }
      - { path: ^/, prefer_extension: true, fallback_format: html, priorities: [ 'html', '*/*'] }